INSERT INTO `drugstoredb`.`doctor` (`ssn`, `first_name`, `last_name`, `practice_since`, `specialty`) VALUES ('123456789', 'Porter', 'Robinson', '1999', 'Pediatric');
INSERT INTO `drugstoredb`.`doctor` (`ssn`, `first_name`, `last_name`, `practice_since`, `specialty`) VALUES ('987654321', 'Joel', 'Zimmerman', '1991', 'Optometry');
INSERT INTO `drugstoredb`.`doctor` (`ssn`, `first_name`, `last_name`, `practice_since`, `specialty`) VALUES ('456789123', 'Soony', 'Moore', '2005', 'Dermatology');
INSERT INTO `drugstoredb`.`drug` (`formula`, `tradeName`) VALUES ('generic1', 'trade1');
INSERT INTO `drugstoredb`.`drug` (`formula`) VALUES ('generic2');
INSERT INTO `drugstoredb`.`drug` (`formula`, `tradeName`) VALUES ('generic3', 'trade3');
INSERT INTO `drugstoredb`.`drug` (`formula`) VALUES ('generic4');
INSERT INTO `drugstoredb`.`drug` (`formula`, `tradeName`) VALUES ('generic5', 'trade5');
INSERT INTO `drugstoredb`.`patient` (`doctor_id`, `ssn`, `first_name`, `last_name`, `birthdate`, `address`) VALUES ('1', '111223333', 'Johnny', 'Walker', '1969-05-09', '123 Main St, San Diego, CA, 92128');
INSERT INTO `drugstoredb`.`patient` (`doctor_id`, `ssn`, `first_name`, `last_name`, `birthdate`, `address`) VALUES ('3', '222334444', 'Captain', 'Morgan', '1993-08-22', '456 Sunset Blvd, Los Angeles, CA, 92006');
INSERT INTO `drugstoredb`.`patient` (`doctor_id`, `ssn`, `first_name`, `last_name`, `birthdate`, `address`) VALUES ('2', '333445555', 'Jim', 'Bean', '1995-03-15', '789 Palm Ave, LongBeach, CA, 93456');
INSERT INTO `drugstoredb`.`patient` (`doctor_id`, `ssn`, `first_name`, `last_name`, `birthdate`, `address`) VALUES ('1', '444556666', 'Jack', 'Daniels', '1994-11-22', '147 Tulip Blvd, Chula Vista, CA, 96541');
INSERT INTO `drugstoredb`.`pharmacompany` (`phoneNum`, `name`) VALUES ('12223334444', 'Big Pharma');
INSERT INTO `drugstoredb`.`pharmacompany` (`phoneNum`, `name`) VALUES ('13334445555', 'Small Pharma');
INSERT INTO `drugstoredb`.`pharmacy` (`phoneNum`, `name`, `address`) VALUES ('14445556666', 'CVS', '741 Rodeo Dr, Los Angeles, CA, 98521');
INSERT INTO `drugstoredb`.`pharmacy` (`phoneNum`, `name`, `address`) VALUES ('15556667777', 'CVS', '987 Something St, San Diego, CA 92101');
INSERT INTO `drugstoredb`.`pharmacy_has_drug` (`drug_id`, `pharmacy_id`, `drugPrice`) VALUES ('1', '1', '24.99');
INSERT INTO `drugstoredb`.`pharmacy_has_drug` (`drug_id`, `pharmacy_id`, `drugPrice`) VALUES ('2', '2', '6.99');
INSERT INTO `drugstoredb`.`pharmacy_has_drug` (`drug_id`, `pharmacy_id`, `drugPrice`) VALUES ('3', '1', '10.99');
INSERT INTO `drugstoredb`.`prescription` (`rxNumber`, `patient_id`, `doctor_id`, `drug_id`, `quantity`, `date`) VALUES ('159753987', '1', '1', '1', '2', '2023-05-11');
INSERT INTO `drugstoredb`.`prescription` (`rxNumber`, `patient_id`, `doctor_id`, `drug_id`, `quantity`, `date`) VALUES ('753951852', '2', '3', '2', '1', '2023-04-16');
INSERT INTO `drugstoredb`.`prescription` (`rxNumber`, `patient_id`, `doctor_id`, `drug_id`, `quantity`, `date`) VALUES ('852456369', '3', '2', '1', '2', '2023-05-01');
INSERT INTO `drugstoredb`.`prescription` (`rxNumber`, `patient_id`, `doctor_id`, `drug_id`, `quantity`, `date`) VALUES ('741852963', '1', '1', '1', '2', '2023-03-13');
INSERT INTO `drugstoredb`.`prescription` (`rxNumber`, `patient_id`, `doctor_id`, `drug_id`, `quantity`, `date`) VALUES ('789147258', '3', '2', '3', '3', '2023-01-31');
INSERT INTO `drugstoredb`.`pharmacompany_makes_drug` (`drug_id`, `pharmaCompany_id`) VALUES ('1', '1');
INSERT INTO `drugstoredb`.`pharmacompany_makes_drug` (`drug_id`, `pharmaCompany_id`) VALUES ('2', '1');
INSERT INTO `drugstoredb`.`pharmacompany_makes_drug` (`drug_id`, `pharmaCompany_id`) VALUES ('3', '2');
INSERT INTO `drugstoredb`.`pharmacompany_makes_drug` (`drug_id`, `pharmaCompany_id`) VALUES ('4', '1');
INSERT INTO `drugstoredb`.`pharmacompany_makes_drug` (`drug_id`, `pharmaCompany_id`) VALUES ('5', '2');
INSERT INTO `drugstoredb`.`contract_pharmacy_pharmacompany` (`pharmacy_id`, `pharmaCompany_id`, `supervisor_firstName`, `supervisor_lastName`, `start_date`, `end_date`, `contract_text`) VALUES ('1', '1', 'Will', 'Smith', '2023-02-28', '2023-03-02', 'We will sell drugs to you.');
INSERT INTO `drugstoredb`.`contract_pharmacy_pharmacompany` (`pharmacy_id`, `pharmaCompany_id`, `supervisor_firstName`, `supervisor_lastName`, `start_date`, `end_date`, `contract_text`) VALUES ('1', '2', 'Will', 'Smith', '2023-04-01', '2023-04-05', 'We will sell drugs to you.');
INSERT INTO `drugstoredb`.`contract_pharmacy_pharmacompany` (`pharmacy_id`, `pharmaCompany_id`, `supervisor_firstName`, `supervisor_lastName`, `start_date`, `end_date`, `contract_text`) VALUES ('2', '2', 'Chris', 'Rock', '2022-09-06', '2022-10-01', 'We will sell drugs to you.');
INSERT INTO `drugstoredb`.`pharmacy_fills_prescription` (`rxNumber`, `pharmacy_id`, `pharmaCompany_id`, `date`, `is_generic_name`) VALUES ('741852963', '1', '1', '2022-02-06', '1');
INSERT INTO `drugstoredb`.`pharmacy_fills_prescription` (`rxNumber`, `pharmacy_id`, `pharmaCompany_id`, `date`, `is_generic_name`) VALUES ('753951852', '2', '1', '2023-04-20', '1');
INSERT INTO `drugstoredb`.`pharmacy_fills_prescription` (`rxNumber`, `pharmacy_id`, `pharmaCompany_id`, `date`, `is_generic_name`) VALUES ('789147258', '1', '2', '2023-05-01', '1');
INSERT INTO `drugstoredb`.`pharmacy_fills_prescription` (`rxNumber`, `pharmacy_id`, `pharmaCompany_id`, `date`, `is_generic_name`) VALUES ('852456369', '1', '1', '2023-05-06', '1');
INSERT INTO `drugstoredb`.`pharmacy_fills_prescription` (`rxNumber`, `pharmacy_id`, `pharmaCompany_id`, `date`, `is_generic_name`) VALUES ('159753987', '1', '1', '2023-05-07', '1');
